# If launch in i3/config the scratchpads are not spawn (race condition?)
urxvtd -o -q -f

# merge .Xressources file
[[ -f .config/X11/xresources ]] && xrdb -merge .config/X11/xresources

# maps caps lock to the escape key AND left control key (for Neovim and because it's so sweet).
setxkbmap -option 'caps:ctrl_modifier';xcape -e 'Caps_Lock=Escape'&

# personnalized keyboard keys
# [[ -f .config/X11/xmodmap ]] && xmodmap .config/X11/xmodmap

exec i3
