vim.cmd([[ let @q="A error\<ESC>gciw"]])
vim.cmd([[ iabbrev xname Hernandez Zacateco Aldo Rene]])
vim.cmd([[ iabbrev xmail zac@ciencias.unam.mx]])
vim.cmd([[ iabbrev xuni  Universidad Nacional Autonoma de Mexico]])
vim.cmd([[ iabbrev xc  ```ts```]])
